In [1]:
!pip install open3d numpy pye57

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detai

In [2]:
import os
import numpy as np
import open3d as o3d
from pye57 import E57
import cv2
import pandas as pd

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [22]:
e57= E57('RawScans\B6 - G.e57')

In [ ]:
data=e57.read_scan(0,intensity=True, colors=True,row_column=True,transform=True,ignore_missing_fields=True)

In [10]:
print(data.keys())

dict_keys(['sphericalRange', 'sphericalAzimuth', 'sphericalElevation', 'intensity', 'colorRed', 'colorGreen', 'colorBlue', 'rowIndex', 'columnIndex', 'cartesianX', 'cartesianY', 'cartesianZ'])


In [11]:
data

{'sphericalRange': array([0.1182, 0.118 , 0.1174, ..., 0.    , 0.    , 0.    ],
       shape=(2366304,)),
 'sphericalAzimuth': array([ 3.14159751,  3.14159751,  3.14159751, ..., -3.14153957,
        -3.14153957, -3.14153957], shape=(2366304,)),
 'sphericalElevation': array([ 1.56911027,  1.56232285,  1.5571636 , ..., -0.77527612,
        -0.78027838, -0.7852807 ], shape=(2366304,)),
 'intensity': array([15139., 11698., 10375., ...,     0.,     0.,     0.],
       shape=(2366304,), dtype=float32),
 'colorRed': array([0, 0, 0, ..., 1, 1, 1], shape=(2366304,), dtype=uint8),
 'colorGreen': array([0, 0, 0, ..., 0, 0, 0], shape=(2366304,), dtype=uint8),
 'colorBlue': array([0, 0, 0, ..., 0, 0, 2], shape=(2366304,), dtype=uint8),
 'rowIndex': array([470, 469, 468, ...,   2,   1,   0], shape=(2366304,), dtype=uint16),
 'columnIndex': array([   0,    0,    0, ..., 5023, 5023, 5023],
       shape=(2366304,), dtype=uint16),
 'cartesianX': array([-0.00019929, -0.00099986, -0.00160043, ..., -0.    

In [12]:
data_raw = e57.read_scan_raw(0)

In [16]:
header = e57.get_header(0)

In [17]:
header

In [18]:
for line in header.pretty_print():
    print(line)


<StringNode 'guid'>: {ea73bf94_23ab_4d71_a433_282d4036bd23}
<StringNode 'name'>: 01-B6-G-SCN0001
<StringNode 'description'>: this file is generated by Autodesk ReCap
<StringNode 'sensorVendor'>: Topcon
<StructureNode 'indexBounds'>
    <IntegerNode 'rowMinimum'>: 0
    <IntegerNode 'rowMaximum'>: 470
    <IntegerNode 'columnMinimum'>: 0
    <IntegerNode 'columnMaximum'>: 5023
    <IntegerNode 'returnMinimum'>: 0
    <IntegerNode 'returnMaximum'>: 0
<StructureNode 'intensityLimits'>
    <IntegerNode 'intensityMaximum'>: 65535
    <IntegerNode 'intensityMinimum'>: 0
<StructureNode 'colorLimits'>
    <IntegerNode 'colorRedMaximum'>: 255
    <IntegerNode 'colorRedMinimum'>: 0
    <IntegerNode 'colorGreenMaximum'>: 255
    <IntegerNode 'colorGreenMinimum'>: 0
    <IntegerNode 'colorBlueMaximum'>: 255
    <IntegerNode 'colorBlueMinimum'>: 0
<StructureNode 'sphericalBounds'>
    <FloatNode 'rangeMinimum'>: 0.0
    <FloatNode 'rangeMaximum'>: 42949.67296
    <FloatNode 'elevationMinimum'>: -0.

In [20]:
print(np.max(data['sphericalRange']))

178.62449645996094


In [24]:
position_scan_0 = e57.scan_position(1)

In [41]:
print(e57.scan_count)

18


In [40]:
for scan in range(e57.scan_count-1):
    print(e57.scan_position(scan+1))

[[ 4.52983811 10.21964449  0.04300391]]
[[-0.15127363  6.73628815 -0.02512015]]
[[ 6.53886158 16.49924687  0.20092987]]
[[ 7.64583636e+00  1.81468569e+01 -8.81893950e-03]]
[[9.89523028 6.93066589 0.0540201 ]]
[[-12.84036455   5.1922128    0.43468325]]
[[-9.28041602  5.377575    0.39976654]]
[[-8.28469065 -1.53126675  0.39992487]]
[[-17.43105932  -1.71933625   0.41456828]]
[[-2.56732851e+01  9.81491950e+00 -9.74208591e-03]]
[[-3.01132910e+01  2.37941246e+00  2.07449129e-02]]
[[-35.05249906   8.15427411   0.04897923]]
[[-22.26685622  -5.23771781  -0.03426926]]
[[-33.40758957  -9.04024209   0.04188103]]
[[-1.75802105e+01  1.26922461e+01 -2.87624095e-03]]
[[-2.39373768 14.10822984 -0.01664471]]
[[-7.41579487  9.90955032  0.03796485]]


In [48]:
for scan in range(e57.scan_count):
    try:
        print(e57.scan_position(scan))
    except:
        data=e57.read_scan(scan, ignore_missing_fields=True)
        points = np.vstack((data['cartesianX'], data['cartesianY'], data['cartesianZ'])).T
        mean_points = np.mean(points, axis=0)
        print("Mean of points:", mean_points)

Mean of points: [0.22520974 0.10760292 0.75936196]
[[ 4.52983811 10.21964449  0.04300391]]
[[-0.15127363  6.73628815 -0.02512015]]
[[ 6.53886158 16.49924687  0.20092987]]
[[ 7.64583636e+00  1.81468569e+01 -8.81893950e-03]]
[[9.89523028 6.93066589 0.0540201 ]]
[[-12.84036455   5.1922128    0.43468325]]
[[-9.28041602  5.377575    0.39976654]]
[[-8.28469065 -1.53126675  0.39992487]]
[[-17.43105932  -1.71933625   0.41456828]]
[[-2.56732851e+01  9.81491950e+00 -9.74208591e-03]]
[[-3.01132910e+01  2.37941246e+00  2.07449129e-02]]
[[-35.05249906   8.15427411   0.04897923]]
[[-22.26685622  -5.23771781  -0.03426926]]
[[-33.40758957  -9.04024209   0.04188103]]
[[-1.75802105e+01  1.26922461e+01 -2.87624095e-03]]
[[-2.39373768 14.10822984 -0.01664471]]
[[-7.41579487  9.90955032  0.03796485]]


In [67]:
!pip install scipy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\halim\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
import laspy
import os
import csv
from scipy.stats import zscore

output_dir = "filtered_las_scans"
os.makedirs(output_dir, exist_ok=True)
csv_file = os.path.join(output_dir, "scan_positions.csv")
limit = 10
z_threshold = 3  # Z-score threshold for outlier removal

# Open CSV file to save scan positions
with open(csv_file, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Scan_ID", "X", "Y", "Z"])  # CSV Header

    for scan in range(e57.scan_count):
        try:
            position = e57.scan_position(scan)
            position = position.flatten().tolist()  # Ensure it's a list [x, y, z]
        except Exception as e:
            print(f"Error retrieving scan position for scan {scan}: {e}")
            data = e57.read_scan(scan, intensity=True, colors=True, row_column=True, transform=True, ignore_missing_fields=True)
            points = np.vstack((data['cartesianX'], data['cartesianY'], data['cartesianZ'])).T

            if points.shape[0] == 0:
                print(f"Skipping scan {scan}: No valid points found.")
                continue  # Skip if there are no valid points

            position = np.mean(points, axis=0).tolist()  # Convert to list
            if len(position) != 3:
                print(f"Skipping scan {scan}: Invalid computed position {position}.")
                continue

        # Save scan position to CSV
        writer.writerow([scan] + position)  # Ensure scan position is written correctly

        data = e57.read_scan(scan, intensity=True, colors=True, row_column=True, transform=True, ignore_missing_fields=True)
        points = np.vstack((data['cartesianX'], data['cartesianY'], data['cartesianZ'])).T
        distances = np.linalg.norm(points - position, axis=1)

        # Apply distance filter
        mask = distances <= limit
        filtered_points = points[mask]

        if 'colorRed' in data and 'colorGreen' in data and 'colorBlue' in data:
            colors = np.vstack((data['colorRed'], data['colorGreen'], data['colorBlue'])).T
            filtered_colors = colors[mask]
            filtered_colors = (filtered_colors * 255).astype(np.uint16)  # Scale colors for LAS format
        else:
            filtered_colors = None

        # Remove outliers using Z-score
        if filtered_points.shape[0] > 0:
            z_scores = np.abs(zscore(filtered_points, axis=0))
            non_outlier_mask = (z_scores < z_threshold).all(axis=1)
            filtered_points = filtered_points[non_outlier_mask]

            if filtered_colors is not None:
                filtered_colors = filtered_colors[non_outlier_mask]

        print(f"Scan {scan}: {points.shape[0]} points before filtering, {filtered_points.shape[0]} points within {limit} meters after filtering and after removing outliers")

        if filtered_points.shape[0] > 0:
            # Create LAS file
            las_header = laspy.LasHeader(point_format=2, version="1.2")
            las = laspy.LasData(las_header)
            las.x, las.y, las.z = filtered_points[:, 0], filtered_points[:, 1], filtered_points[:, 2]

            if filtered_colors is not None:
                las.red, las.green, las.blue = filtered_colors[:, 0], filtered_colors[:, 1], filtered_colors[:, 2]

            las_path = os.path.join(output_dir, f"filtered_scan_{scan}.las")
            las.write(las_path)
            print(f"Filtered scan {scan} saved as {las_path}")

print(f"All scan positions saved to {csv_file}")


Error retrieving scan position for scan 0: E57 element path well formed but not defined (ErrorPathUndefined)

**** Got an e57 exception: E57 element path well formed but not defined (ErrorPathUndefined)
  Debug info: 
    context: this->pathName=/data3D/0 pathName=pose
    sourceFunctionName: e57::StructureNodeImpl::get
    reportingFunctionName: pybind11_init_libe57::<lambda_1>::<lambda_invoker_cdecl>
D:\a\pye57\pye57\libE57Format\src\StructureNodeImpl.cpp(145) : error C22:  <--- occurred on
src/pye57/libe57_wrapper.cpp(49) : error C0:  <--- reported on

Scan 0: 2366304 points before filtering, 2268353 points after filtering and removing outliers


E57Exception: E57 element path well formed but not defined (ErrorPathUndefined)

**** Got an e57 exception: E57 element path well formed but not defined (ErrorPathUndefined)
  Debug info: 
    context: this->pathName=/data3D/0 pathName=pose
    sourceFunctionName: e57::StructureNodeImpl::get
    reportingFunctionName: pybind11_init_libe57::<lambda_1>::<lambda_invoker_cdecl>
D:\a\pye57\pye57\libE57Format\src\StructureNodeImpl.cpp(145) : error C22:  <--- occurred on
src/pye57/libe57_wrapper.cpp(49) : error C0:  <--- reported on
